spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  cloud:
    config:
      enabled: false

server:
  port: 8082

app:
  clients:
    greeting-service:
      - localhost:8095
      - localhost:8096
    another-service:
      - localhost:8055
      - localhost:8056